# Generated by Django 4.0.5 on 2022-06-22 20:31

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='parent',
            field=mptt.fields.TreeManyToManyField(blank=True, to='mandala_shop.goods'),
        ),
    ]
