# Generated by Django 4.0.5 on 2022-06-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_shop', '0007_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='count',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(to='mandala_shop.goods'),
        ),
    ]
