# Generated by Django 4.0.5 on 2022-08-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_shop', '0008_basket_count_basket_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['type_weight', 'weight'], 'verbose_name': 'Вес', 'verbose_name_plural': 'вес'},
        ),
        migrations.RenameField(
            model_name='weight',
            old_name='type_wight',
            new_name='type_weight',
        ),
    ]
